// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ExternalPlatformIdController from "./external_platform_id_controller"
application.register("external-platform-id", ExternalPlatformIdController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
